server:
  port: 8080
  servlet:
    context-path: /bookstore

spring:
  datasource:
    url: "jdbc:mysql://localhost:3308/bookstore1"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "+sKONebNUcmUmf+npmjczX4luDnOk4troBnQMmhVxqp64MSKvk5XrVe2Ijr1X+qS"
  valid-duration: 3600 #in second
  refreshable-duration: 36000 # in seconds


payment:
  vnPay:
    url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
    tmnCode: "EFAXRVFK"
    secretKey: "H2LZYC57EI28HPVTR4H13HTKM682U60E"
    returnUrl: "http://localhost:8080/bookstore/payment/vn-pay-callback"
    version: 2.1.0
    command: "pay"
    orderType: "other"
    queryUrl: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"
